apiVersion: apps/v1
kind: Deployment
metadata:
  name: contracts
  labels:
    component: contracts
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: contracts
      tier: backend
  template:
    metadata:
      labels:
        component: contracts
        tier: backend
    spec:
      containers:
        - name: contracts
          image: contracts.dev
          imagePullPolicy: Never
          ports:
            - containerPort: 8485
