name: Publish Developer Docs

on:
  push:
    branches: [main]
    paths:
      - 'apps/developer-docs/**'

jobs:
  release:
    name: Deploy docs

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - run: pnpm install
      - run: pnpx nx build developer-docs

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          repository-name: SolomonDefi/solomondefi.github.io
          branch: gh-pages
          folder: dist/apps/developer-docs
